Module_2
Ana-Kalandadze/DQE-Intermediate pull request #2
Opened 2024-03-06 11:12 UTC by Ana-Kalandadze

2024-03-12 05:47 UTC, elamani requested changes

2024-03-12 05:47 UTC, elamani commented on Module_2/test_cases_dq_checks.xlsx
Please add scenarios for Incremental load validations

2024-03-13 12:23 UTC, Ana-Kalandadze commented on Module_2/test_cases_dq_checks.xlsx
I have updated/added scenarios 30-37 for incremental load.

2024-03-14 05:33 UTC, elamani approved these changes

2024-03-14 07:04 UTC, merged